# Generated by Django 3.1.7 on 2021-03-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carriers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='description',
        ),
        migrations.AddField(
            model_name='profession',
            name='long_desc',
            field=models.CharField(default='PLACEHOLDER', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profession',
            name='short_desc',
            field=models.CharField(default='PLACEHOLDER', max_length=200),
            preserve_default=False,
        ),
    ]
