# Generated by Django 3.1.7 on 2021-03-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carriers', '0003_personalitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitytype',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profession',
            name='long_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profession',
            name='short_desc',
            field=models.CharField(max_length=500),
        ),
    ]
