# Generated by Django 3.1.7 on 2021-03-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carriers', '0004_auto_20210308_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalitytype',
            name='image_path',
        ),
    ]
